### ISSUE TITLE
[request] add more sources

### ISSUE THREAD

**Issue by boeboe** [zant95/hMirror#1]
Hi @zant95 

Would you mind adding a few extra sources (for example those for unwanted mining sites).

A huge list can be found here:
http://www.ubuntuboss.com/how-to-install-pihole-on-ubuntu-16-04

**Comment by zant95** [comment]
Hi, I've added more sources and experimental support for parsing AdBlock filters. I'm going to check these new sources in the next few days and maybe add some to [hBlock](https://github.com/zant95/hBlock).

**Comment by boeboe** [comment]
Nice, thanks a lot for the feedback and great tool @zant95 !
